CREATE TABLE
	IF NOT EXISTS users (
		user_name TEXT NOT NULL UNIQUE,
		email TEXT NOT NULL UNIQUE,
		aadhar TEXT NOT NULL,
		password TEXT NOT NULL,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
		deleted_at DATETIME DEFAULT NULL
	);